query getMediaList ($user: Int, $type: MediaType, $sort: [MediaListSort]) {
  MediaListCollection(userId: $user, , type: $type, status_in: [CURRENT, PLANNING, COMPLETED], perChunk: 500, sort: $sort) {
    lists {
      name
      entries {
        score
        progress
        progressVolumes
        media {
          id
          format
          nextAiringEpisode {
            timeUntilAiring
          }
          season
          seasonYear
          episodes
          chapters
          volumes
          siteUrl
          description
          coverImage {
            large
            color
          }
          title {
            english
            romaji
            native
          }
          startDate {
            year
            month
            day
          }
        }
      }
    }
  }
}
